### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by jeffreysbrother** [Sebastian-Fitzner/veams.org#2]
A minor issue, but veams.org encourages us to report typos.

[This](http://www.veams.org/installation.html) page says:

> Veams (or better Veams-Cli) bases on NodeJS.

"bases" should be "based"
Depending on what exactly is trying to be communicated, you might want to say "is based"

**Comment by Sebastian-Fitzner** [comment]
Sorry for the late response but I was in parental leave for over a month. Now I am back in town ;). 

I will fix this asap. Thx for the hint.

**Comment by Sebastian-Fitzner** [comment]
Fixed!
