### ISSUE TITLE
Veams.org throws https warning

### ISSUE THREAD

**Issue by fuzinato** [Sebastian-Fitzner/veams.org#7]
Veams.org throws an non-secure warning. I wonder if you had same issues with let's encrypt and manually renewing SSL certificate as I did :) . Have you consider switching to https://www.netlify.com/ ?( CDN, SSL, CD... for free), and for open-source project you get free pro account ;)

**Comment by Sebastian-Fitzner** [comment]
I will definitely take a look at that ... Thanks for mentioning it and keep up the good work.
